title: D&D at the Library
email: mark@spookydungeon.boo
description: >- # this means to ignore newlines until "baseurl:"
  I will be hosting a Dungeons and Dragons game with my children at the local library. (We are not associate with them, just using their space)
  We are open to other players joining! If your kids would like to join in please reach out to me. Currently looking for others around my kids age. 
  So 9-16 would be great, but if you have someone who really wants to join outside of that range I am open to discuss it! Please check out the Contact Me page to reach out with any questions.
url: "https://spookydungeon.boo" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Felivath
theme: null
markdown: kramdown

